### ISSUE TITLE
capacity of assign_range

### ISSUE THREAD

**Issue by oouazize** [Mikastiv/ft_containers-terminator#3]
Hello, if you want to add it, there is one more test that concerns the assign_range (and ctor_range) capacity
The input iterator and the random access iterator use different techniques of allocating

The first one (input iterator) uses the push-back method, so, the capacity will double as the size becomes equal to it
The second one (random access iterator) will allocate as far as the range distance

**WHAT WILL I ADD?**

Use PRINT_CAPACITY instead of CHECK_CAPACITY

It will be more efficient, the tester will return KO if the user has not dealt with this

**Comment by mikastiv** [comment]
That is what I did at first, but because the capacity increase is not required to be doubled, I chose to only check if its greater or equal than size. Also, depending on which STL (libc++, libstdc++, etc.) implementation you are using when testing, it can behave differently so you will have different results.

**Comment by oouazize** [comment]
In general, you're right, it will depend on the STL, but particularly in our project using MacOS and whatever compiler we can test (g++, c++, clang++, etc.), there is no problem, at least the user will know the implementation is different according to the arguments

**Comment by mikastiv** [comment]
A different implementation isn't necessarily wrong, so I don't want the tester to show a KO.

**Comment by oouazize** [comment]
Ok
